### ISSUE TITLE
git-lfs-migrate broken, always errors out with "exit status 128" to stderr and errcode 2

### ISSUE THREAD

**Issue by ryran** [git-lfs/git-lfs#2534]
```
╔═[rsaw@xala 20:53 myrepo] {0} $ git-lfs migrate import -I '*.png'
exit status 128
╔═[rsaw@xala 20:53 myrepo] {2} $ git-lfs migrate info
exit status 128
╔═[rsaw@xala 20:53 myrepo] {2} $ 
```

In other news: I just read through #2146 and it seemed the consensus was to have `convert` & `revert` subcommands ... this sounds awesome and like exactly what I want.

Unfortunately, the man page mentions nothing of these; only `import`. What's that about?

**Comment by ttaylorr** [comment]
Hi @ryran! Thanks for opening this issue, and sorry that you're having trouble. Can you share a copy of your repository so I can figure out where that `exit status 128` is coming from? If not, can you re-run the command with `GIT_TRACE=1` in your environment and post the output here?

> In other news: I just read through #2146 and it seemed the consensus was to have `convert` & `revert` subcommands ... this sounds awesome and like exactly what I want.
> 
> Unfortunately, the man page mentions nothing of these; only `import`. What's that about?

Good question! We decided to name the `convert`/`revert` commands `import` and `export` respectively. The `import` migration mode is the only one that we shipped in the latest version, but I am hoping to add support for the `export` mode soon. It didn't quite make the first cut 😄.

**Comment by ttaylorr** [comment]
Hi @ryran, I'm going to close this issue for now since I haven't heard from you. Hopefully the issue is resolved on your end. If it isn't, please comment back here and we can take another look into things.

**Comment by MnTronslien** [comment]
Hi, I might be having a similar issue but not being to fluent in git in the first place I am not to sure.
When i try to migrate .jpeg i get the exit code 128. message.
`$ git lfs migrate import --include="*.jpeg"`
 `exit status 128`
You asked for GIT_TRACE=1, I don't know to run the command, but I'll run it if you give me something i can copy-paste into the shell.

**Comment by ttaylorr** [comment]
> You asked for GIT_TRACE=1, I don't know to run the command, but I'll run it if you give me something i can copy-paste into the shell.

Hi @MnTronslien -- thanks for commenting here 👍. Here's something to paste into your shell:

```sh
GIT_TRACE=1 git lfs migrate import --include="*.jpeg"
```

**Comment by MnTronslien** [comment]
Hello and thanks for the quick reply! It turned out to be a simple thing and I solved it. It was simply missing credentials I think, but it never prompted me for them. Updating the URL with username made it prompt me when migrating, and that made the migrate complete. This is a problem that has been haunting my team for about two weeks now so this was an awesome breakthrough for us!
(Still don't know where i set the git URL in bash but i managed to change it through SmartGit)

Here is the Git_trace before adding credentials: 

`$ GIT_TRACE=1 git lfs migrate import --include="*.jpeg"
16:11:01.754235 git.c:564               trace: exec: 'git-lfs' 'migrate' 'import' '--include=*.jpeg'
16:11:01.754725 run-command.c:336       trace: run_command: 'git-lfs' 'migrate' 'import' '--include=*.jpeg'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' rev-parse master --symbolic-full-name master
exit status 128
`

And here it is after:

`$ GIT_TRACE=1 git lfs migrate import --include="*.jpeg"
16:12:32.449825 git.c:564               trace: exec: 'git-lfs' 'migrate' 'import' '--include=*.jpeg'
16:12:32.450330 run-command.c:336       trace: run_command: 'git-lfs' 'migrate' 'import' '--include=*.jpeg'
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: run_command: 'git' rev-parse HEAD --symbolic-full-name HEAD
trace git-lfs: run_command: 'git' rev-parse master --symbolic-full-name master
trace git-lfs: run_command: git rev-list --reverse --topo-order --do-walk master ^refs/remotes/origin/feature/[redacted] ^refs/remotes/origin/feature/Networking ^refs/remotes/origin/master --
migrate: Sorting commits: ..., done
migrate: Rewriting commits: NaN% (0/0), done
migrate: Updating refs: ..., done
trace git-lfs: run_command: 'git' rev-parse --is-bare-repository
trace git-lfs: run_command: 'git' checkout --force
`

So in the end i might suggest adding  some sort of error message for bad credentials other than exit status 128? because that link was hard to find :S Ofc only if its a lfs and not a git thing.

**Comment by ttaylorr** [comment]
I'm glad that you were able to get it to work 👍.

> So in the end i might suggest adding some sort of error message for bad credentials other than exit status 128? because that link was hard to find :S Ofc only if its a lfs and not a git thing.

Great call -- I'll look at adding something like this. Thanks again!

**Comment by ttaylorr** [comment]
@BDeschenes I think that as far as the `git lfs migrate` tool is concerned this may be working as intended. The idea is that `git lfs migrate` should, by default, not migrate anything that would require a force push to send to the remote. In other words, `git lfs migrate` should not migrate over anything that isn't already on the remote.

So, to be on the safe side, Git LFS will skip migrating anything that is present on _any_ remote. (For reference, [here][1] is the place where that data is aggregated).

One thing that I think we could do to make this behavior more reasonable is teach `git lfs migrate` a `--remote` option, which would narrow this scope to only the set of included remotes. So, instead of saying something like `git lfs migrate info --include-ref=refs/remotes/origin/master`, you could just say `git lfs migrate info --{include,exclude}-remote=origin` and it would automatically include/exclude all remote references pertaining to that remote.

What do you think?

[1]: https://github.com/git-lfs/git-lfs/blob/master/commands/command_migrate.go#L188-L229
