### ISSUE TITLE
Git LFS Windows installer does not update Git LFS installed by Git for Windows

### ISSUE THREAD

**Issue by larsxschneider** [git-lfs/git-lfs#2587]
Git for Windows installs (by default, but optionally) `git-lfs.exe` into `C:\Program Files\Git\mingw64\bin`. Even if Git LFS is installed by Git for Windows, Git LFS will install itself to `C:\Program Files\Git LFS`.

This can lead to two different versions of Git LFS on a single machine. Git will use the version that "earlier" in the PATH I think.

Is this expected/known?

//cc @sschuberth

**Comment by sschuberth** [comment]
I just noticed the same thing today. I don't think that's the wanted behavior, as people may want to upgrade the Git LFS version bundled with Git for Windows by manually installing native Git LFS.

I believe that can be easily fixed by swapping the order of `{olddata}` and `{app}` in

https://github.com/git-lfs/git-lfs/blob/4dd2bf73d7819733f7d8cc29a8e8404fc0552242/script/windows-installer/inno-setup-git-lfs-installer.iss#L55

and

https://github.com/git-lfs/git-lfs/blob/4dd2bf73d7819733f7d8cc29a8e8404fc0552242/script/windows-installer/inno-setup-git-lfs-installer.iss#L57

That way running the Git LFS installed will give its `git-lfs` binary precedence over any binary form Git for Windows.

**Comment by ttaylorr** [comment]
@sschuberth @larsxschneider thanks for posting this, we should definitely not encourage paths where users can have two copies of LFS installed on their machines... this leads to lots of confusing issues :).

@sschuberth can you turn the above into a patch and verify that it works? There's no rush to this, of course, and totally optional if you want to pass on this, but your expertise here would be greatly appreciated.

**Comment by ttaylorr** [comment]
@sschuberth Are you still interested in working on this? I'd love to fix this within a few releases.

**Comment by sschuberth** [comment]
@ttaylorr After giving my original idea a try in #2589 and realizing it does not work, and it requires significant effort to get fixed properly, I dropped the ball on this one. Sorry for not communicating this more clearly!

**Comment by ttaylorr** [comment]
> Sorry for not communicating this more clearly!

Not a worry, I've moved this to the backlog for now, but let me know if you'd like to work on it again in the future and I can schedule it for a release then.

**Comment by Socolin** [comment]
Hello,

I have the same problem but with on an azure webapp where I can't update git version. Their version of git lfs is an old one 2.5.2 with bugs that were fixed in git lfs 2.7.1.
Azure provide a directory that is the first in the PATH variable to add additional binaries

```
echo $env:PATH
D:\home\site\deployments\tools;[...];;D:\Program Files (x86)\Git\cmd;[...]
```

If I put a newer version of `git-lfs` in this directory it seems to be detected as expected
```
$ which git-lfs
/d/home/site/deployments/tools/git-lfs
$ git-lfs --version
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.2; git 30af66bb)
```

but when I run `git lfs` I got that
```
$ git lfs version
git-lfs/2.5.2 (GitHub; windows amd64; go 1.10.3; git 8e3c5c93)
```

From what I understand `git lfs` should call the first `git-lfs.exe` it found following the given paths in `PATH` but it don't seems to be doing that here.

Is there a way to so `git checkout` will use the latest git lfs version ?

**Comment by bk2204** [comment]
I believe Git will use its built-in `GIT_EXEC_PATH` before the system `PATH`. If you run `git --exec-path`, and there's a `git-lfs` or `git-lfs.exe` binary in there, then you'd need to overwrite that version, since Git will always use it by default.

**Comment by gdlxn-ibm** [comment]
I was also having this problem.  I had two `git-lfs.exe` binaries which I replace with the latest Git LFS build:

```
C:\WINDOWS\system32>where git-lfs
C:\Program Files\Git LFS\git-lfs.exe
C:\Program Files\Git\cmd\git-lfs.exe
```

Even after updating both of these binaries with the latest build version, `git lfs --version` was still showing the old Git LFS version:

```
C:\WINDOWS\system32>git lfs --version
git-lfs/2.7.2 (GitHub; windows amd64; go 1.12.2; git 08a08ae0)
```

I tried running `git --exec-path` as suggested:

```
C:\WINDOWS\system32>git --exec-path
C:/Program Files/Git/mingw64/libexec/git-core
```

The `C:/Program Files/Git/mingw64/libexec/git-core` directory **does not** contain a `git-lfs.exe` binary.  

After recursively searching the ``C:/Program Files/Git` directory, I found another `git-lfs.exe` binary in `C:\Program Files\Git\mingw64\bin`.  After replacing this `git-lfs.exe` with the latest build version, `git lfs --version` now shows the new build version:

```
C:\WINDOWS\system32>git lfs --version
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.7; git bb05cf50)

**Comment by feinstein** [comment]
Do we have any updates on this?

There's a big warning in the git lfs webside about a security update, people will update and think the binaries will be safe now, but they would still be executing the old version.

**Comment by feinstein** [comment]
I see... unfortunately I am not familiar with it either :/
