### ISSUE TITLE
git lfs does not respect custom port og https while authentification via ssh and git-lfs-authentificate

### ISSUE THREAD

**Issue by nqdrizzt** [git-lfs/git-lfs#2618]
Versions:

git client: 
$ git --version
git version 2.14.1.windows.1
git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)

git server:
mayerdir@odin:~$ git --version
git version 2.14.1
git-lfs/2.2.1 (GitHub; linux amd64; go 1.8.3)
running patched **https** lfs-test-server on port **9999** with git-lfs-authentificate which integrates into goitolite

After running a initial git lfs push successfully the second push fails with error message: Authentification required. The reason for that is, that git automatically updates the .git/config file withe verifyssl= false and authentification basic=true. But during This reconfiguration it ignores the custom port https port 9999 in the config file. After adding the correct port in the .git/config file the push works again **one** time until it gets reconfigured again. also the git client is ignoring this setting in the .lfsconfig file

```
$ git lfs env
git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)
git version 2.14.1.windows.1

Endpoint=https://172.17.31.252/systec_bin4.git (auth=none)
  SSH=git@172.17.31.252:systec_bin4.git
LocalWorkingDir=C:\_MyWork\Git\systec_bin4
LocalGitDir=C:\_MyWork\Git\systec_bin4\.git
LocalGitStorageDir=C:\_MyWork\Git\systec_bin4\.git
LocalMediaDir=C:\_MyWork\Git\systec_bin4\.git\lfs\objects
LocalReferenceDir=
TempDir=C:\_MyWork\Git\systec_bin4\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_SSH=C:\Program Files\Git\usr\bin\ssh.exe
git config filter.lfs.process = "git-lfs filter-process --skip"
git config filter.lfs.smudge = "git-lfs smudge --skip -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
```

running the git lfs push the first time:
```
$ GIT_CURL_VERBOSE=1 GIT_TRACE=true git lfs push origin master
08:54:46.223280 git.c:560               trace: exec: 'git-lfs' 'push' 'origin' 'master'
08:54:46.223280 run-command.c:626       trace: run_command: 'git-lfs' 'push' 'origin' 'master'
trace git-lfs: run_command: 'git' config -l -f C:\_MyWork\Git\systec_bin4\.lfsconfig
trace git-lfs: run_command: 'git' config -l
trace git-lfs: run_command: 'git' version
trace git-lfs: tq: running as batched queue, batch size of 100
trace git-lfs: run_command: C:\Program Files\Git\usr\bin\ssh.exe -- git@172.17.31.252 git-lfs-authenticate systec_bin4.git upload
trace git-lfs: HTTP: POST https://172.17.31.252:9999/systec_bin4.git/locks/verify
> POST /systec_bin4.git/locks/verify HTTP/1.1
> Host: 172.17.31.252:9999
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: RemoteAuth  ........secret key...................
> Content-Length: 2
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)
>
{}trace git-lfs: HTTP: 404


< HTTP/1.1 404 Not Found
< Content-Length: 19
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 27 Sep 2017 06:55:38 GMT
< X-Content-Type-Options: nosniff
<
trace git-lfs: commands: disabling lock verification for "https://172.17.31.252/systec_bin4.git"
trace git-lfs: run_command: **'git' config lfs.https://172.17.31.252/systec_bin4.git.locksverify false**
trace git-lfs: Upload refs [master] to remote origin
trace git-lfs: run_command: git rev-list --objects master --not --remotes=origin --
trace git-lfs: run_command: git cat-file --batch-check
trace git-lfs: run_command: git cat-file --batch
trace git-lfs: tq: sending batch of size 2
trace git-lfs: run_command: C:\Program Files\Git\usr\bin\ssh.exe -- git@172.17.31.252 git-lfs-authenticate systec_bin4.git upload
trace git-lfs: api: batch 2 files
trace git-lfs: HTTP: POST https://172.17.31.252:9999/systec_bin4.git/objects/batch
> POST /systec_bin4.git/objects/batch HTTP/1.1
> Host: 172.17.31.252:9999
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: RemoteAuth  ........secret key...................
> Content-Length: 216
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)
>
{"operation":"upload","objects":[{"oid":"2fb105f29365d79aaccca88fa960eb07c92b3e9bf40f210d32e9cc44886932cd","size":41110680},{"oid":"0dc556503e3ce4699228fc910a8e4a8d81172635ac8e8e16a11be107254c4901","size":37255040}]}trace git-lfs: HTTP: 401


< HTTP/1.1 401 Unauthorized
< Content-Length: 26
< Content-Type: text/plain; charset=utf-8
< Date: Wed, 27 Sep 2017 06:55:39 GMT
< Www-Authenticate: Basic realm=git-lfs-server
<
trace git-lfs: setting repository access to basic
trace git-lfs: run_command: 'git' config lfs.https://172.17.31.252/systec_bin4.git.access basic
trace git-lfs: api: http response indicates "basic" authentication. Resubmitting...
trace git-lfs: creds: git credential fill ("https", "172.17.31.252:9999", "systec_bin4.git/objects/batch")
trace git-lfs: Filled credentials for https://172.17.31.252:9999/systec_bin4.git/objects/batch
trace git-lfs: HTTP: POST https://172.17.31.252:9999/systec_bin4.git/objects/batch
> POST /systec_bin4.git/objects/batch HTTP/1.1
> Host: 172.17.31.252:9999
> Accept: application/vnd.git-lfs+json; charset=utf-8
> Authorization: Basic * * * * *
> Content-Length: 216
> Content-Type: application/vnd.git-lfs+json; charset=utf-8
> User-Agent: git-lfs/2.2.1 (GitHub; windows amd64; go 1.8.3; git 621d1f82)
>
{"operation":"upload","objects":[{"oid":"2fb105f29365d79aaccca88fa960eb07c92b3e9bf40f210d32e9cc44886932cd","size":41110680},{"oid":"0dc556503e3ce4699228fc910a8e4a8d81172635ac8e8e16a11be107254c4901","size":37255040}]}{"operation":"upload","objects":[{"oid":"2fb105f29365d79aaccca88fa960eb07c92b3e9bf40f210d32e9cc44886932cd","size":41110680},{"oid":"0dc556503e3ce4699228fc910a8e4a8d81172635ac8e8e16a11be107254c4901","size":37255040}]}trace git-lfs: HTTP: 200


< HTTP/1.1 200 OK
< Content-Length: 766
< Content-Type: application/vnd.git-lfs+json
< Date: Wed, 27 Sep 2017 06:55:40 GMT
<
trace git-lfs: HTTP: {"objects":[{"oid":"2fb105f29365d79aaccca88fa960eb07c92b3e9bf40f210d32e9cc44886932cd","size":41110680,"actions":{"download":{"href":"https://172.17.31.252:9999/systec_bin4.git/objects/2fb105f29365d79aaccca88fa960eb07c92b3e9bf40f210d32e9cc44886932cd","header":{"Accept":"application/vnd.git-lfs","Authorization":"Basic ........secret key................... "},"expires_at":"0001-01-01T00:00:00Z"}}},{"oid":"0dc556503e3ce4699228fc910a8e4a8d81172635ac8e8e16a11be107254c4901","size":37255040,"actions":{"download":{"href":"htt
{"objects":[{"oid":"2fb105f29365d79aaccca88fa960eb07c92b3e9bf40f210d32e9cc44886932cd","size":41110680,"actions":{"download":{"href":"https://172.17.31.252:9999/systec_bin4.git/objects/2fb105f29365d79aaccca88fa960eb07c92b3e9bf40f210d32e9cc44886932cd","header":{"Accept":"application/vnd.git-lfs","Authorization":"Basic  ........secret key..................."},"expires_at":"0001-01-01T00:00:00Z"}}},{"oid":"0dc556503e3ce4699228fc910a8e4a8d81172635ac8e8e16a11be107254c4901","size":37255040,"actions":{"download":{"href":"htttrace git-lfs: HTTP: ps://172.17.31.252:9999/systec_bin4.git/objects/0dc556503e3ce4699228fc910a8e4a8d81172635ac8e8e16a11be107254c4901","header":{"Accept":"application/vnd.git-lfs","Authorization":"Basic  ........secret key..................."},"expires_at":"0001-01-01T00:00:00Z"}}}]}

ps://172.17.31.252:9999/systec_bin4.git/objects/0dc556503e3ce4699228fc910a8e4a8d81172635ac8e8e16a11be107254c4901","header":{"Accept":"application/vnd.git-lfs","Authorization":"Basic  ........secret key..................."},"expires_at":"0001-01-01T00:00:00Z"}}}]}
trace git-lfs: tq: starting transfer adapter "basic"
Git LFS: (0 of 0 files, 2 skipped) 0 B / 0 B, 74.74 MB skipped
```

From the log i can see that the following command is running
```
trace git-lfs: run_command: **'git' config lfs.https://172.17.31.252/systec_bin4.git.access basic**
```
Here the port 9999 is ignored. The same goes for the sslverify command

now my .git/config looks like that:
```
...
[lfs "https://172.17.31.252/systec_bin4.git"]
        locksverify = false
        access = basic
....
```

Here I miss the custom https port 9999. After manually editing the config file and running the push command again, the config files looks like that:
```
[lfs "https://172.17.31.252:9999/systec_bin4.git"]
        locksverify = false
        access = basic
[lfs "https://172.17.31.252/systec_bin4.git"]
        locksverify = false
        access = basic
```

Also the setting including the custom port in the .lfsconfig file gets ignored

**Comment by technoweenie** [comment]
Thanks for the report. What's the output of the SSH command? `C:\Program Files\Git\usr\bin\ssh.exe -- git@172.17.31.252 git-lfs-authenticate systec_bin4.git upload`

Is that returning an href with the port?

**Comment by technoweenie** [comment]
Okay, I did some digging, and managed to replicate the issue. TLDR: based on your output, the `git-lfs-authenticate` command is returning a new href with a custom port AND an `Authorization: RemoteAuth ...` header that doesn't seem to work. Either remove the bad `Authorization` header or fix it to resolve this issue. I think that change will have to be made in gitolite.

First, LFS is setting your config with that bogus https url on purpose. This way the setting is for the remote itself, and not whatever href is returned from the `ssh git-lfs-authenticate` call. If anything, it should be fixed to use the SSH url, instead of that bogus https url. I don't think that change would help your situation though.

> After running a initial git lfs push successfully the second push fails with error message: Authentification required. The reason for that is, that git automatically updates the .git/config file withe verifyssl= false and authentification basic=true.

This isn't completely accurate. First, `verifyssl` is not set by LFS, but I'm assuming this is a typo and you meant `locksverify`. Also, setting `lfs.<url>.access=basic` does not cause auth required errors. All it does is skips an initial HTTP request without any access, because a previous attempt revealed that this endpoint does need auth. So, it skips an unnecessary request.

Based on your output, it looks like this is what's happening:

* First `push`
  * `locks/verify` call attempted. Server returns 404, so `locksverify` is set to `false`, ensuring it's never attempted again for this remote.
  * `objects/batch` call attempted. SSH `git-lfs-authenticate` returns new url with custom port, and `Authorization: RemoteAuth ...` header. API all returns 401.
  * There's a quirk here that since it's the first attempt, the `access` is changing from `none` to `basic`. So LFS deletes the `Authorization: RemoteAuth ...` header and tries again. The git credential helper is now used to attempt to get a password. If it doesn't have it, you'll be prompted for it.
* Second `push`
  * `locks/verify` call skipped.
  * `objects/batch` call attempted. SSH `git-lfs-authenticate` returns new url with custom port, and `Authorization: RemoteAuth ...` header. API all returns 401.
  * The `access` didn't change, and no credentials were fetched from your git credential helper. Game over :(

I think there are two issues here:

1. Your `ssh git-lfs-authenticate` call is returning an `Authorization: RemoteAuth` header that doesn't work. It should be fixed, or removed if you want the user to use their git credential helper.
2. The auth code has a quirk where the first request asks the git credential helper because the access is being changed from `none` to `basic`.

**Comment by technoweenie** [comment]
> But what is a bit confusing for me, is the `href` thing returned by the token. Shouldn't this be added to the `.git/config` file ?

That's a good idea. In theory, you could run `git config remote.origin.lfsurl <href>`, and skip the SSH command altogether in future LFS commands. However, there are a couple reasons we don't:

1. We can't guarantee that users that prefer ssh remotes have their git credentials set up. 
2. This forces the `href` to be accessible by the user with their git credentials. It may be the case (it is for GitHub), but I don't know if it's _always_ the case.
3. A dynamic `git-lfs-authenticate` response let us run user tests, such as pointing a % of users to a new service. Though this is less important, there are other ways to achieve this of course.

**Comment by Scorpio86** [comment]
I met same issue, but the ` C:\Program Files\Git\usr\bin\ssh.exe -- git@172.17.31.252 git-lfs-authenticate systec_bin4.git upload`
 returns herf without custom port, and the herf starts with http, instead of https.
I attemted with git config remote.origin.lfsurl <href>, but it doesn't work, the PUT herf and port still incorrect.

**Comment by bk2204** [comment]
It really depends on the server that you're using and how it's configured.  I'd look in the documentation for whatever server you're running.
