### ISSUE TITLE
Push to local repository on Windows fails

### ISSUE THREAD

**Issue by gdlxn-ibm** [git-lfs/git-lfs#3742]
I created a local repository on Windows 10 which contains some Git-LFS files. I then attempted to push that repository to another repository on the same system. The `git push` failed:

```
c:\r2g-wd-git-issue-103\git-issue-103>git push origin git-issue-103-stream
10:16:43.444566 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:16:43.452588 git.c:439               trace: built-in: git push origin git-issue-103-stream
10:16:43.454629 run-command.c:663       trace: run_command: unset GIT_PREFIX; 'git-receive-pack '\''C:/r2g-wd-git-issue-103/git-issue-103.git'\'''
10:16:43.575459 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:43.585551 git.c:439               trace: built-in: git receive-pack C:/r2g-wd-git-issue-103/git-issue-103.git
10:16:43.605668 run-command.c:663       trace: run_command: .git/hooks/pre-push origin C:/r2g-wd-git-issue-103/git-issue-103.git
10:16:43.764718 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
10:16:43.766737 git.c:704               trace: exec: git-lfs pre-push origin C:/r2g-wd-git-issue-103/git-issue-103.git
10:16:43.766737 run-command.c:663       trace: run_command: git-lfs pre-push origin C:/r2g-wd-git-issue-103/git-issue-103.git
10:16:44.353444 trace git-lfs: exec: git 'version'
10:16:44.423417 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:16:44.609065 trace git-lfs: exec: git 'config' '-l'
10:16:44.649649 trace git-lfs: pre-push: refs/heads/git-issue-103-stream 740f7c4eef42342120eb2ebc95d8144ac20f4ace refs/heads/git-issue-103-stream 0000000000000000000000000000000000000000
10:16:44.821586 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:16:47.396485 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 0/6)
10:16:47.396485 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:16:49.737675 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 1/6)
10:16:49.737675 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:16:52.234572 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 2/6)
10:16:52.234572 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:16:54.570951 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 3/6)
10:16:54.570951 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:16:57.047756 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 4/6)
10:16:57.047756 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:16:59.394283 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 5/6)
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://c////r2g-wd-git-issue-103/git-issue-103.git/info/lfs.locksverify false
10:16:59.394283 trace git-lfs: tq: running as batched queue, batch size of 100
10:16:59.395281 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=origin --
10:16:59.463586 trace git-lfs: tq: sending batch of size 1
10:16:59.463586 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:17:01.812323 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 0/6)
10:17:01.812323 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:17:04.299273 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 1/6)
10:17:04.299273 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:17:06.656220 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 2/6)
10:17:06.656220 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:17:09.021487 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 3/6)
10:17:09.021487 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:17:11.488424 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 4/6)
10:17:11.488424 trace git-lfs: run_command: ssh -- c git-lfs-authenticate ///r2g-wd-git-issue-103/git-issue-103.git upload
10:17:13.834327 trace git-lfs: ssh: c failed, error: exit status 255, message: ssh: Could not resolve hostname c: Name or service not known (try: 5/6)
batch request: ssh: Could not resolve hostname c: Name or service not known: exit status 255
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done
error: failed to push some refs to 'C:/r2g-wd-git-issue-103/git-issue-103.git'
```

Here's `git remote -v` output:

```
c:\r2g-wd-git-issue-103\git-issue-103>git remote -v
10:18:45.898839 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:18:45.898839 git.c:439               trace: built-in: git remote -v
origin  C:/r2g-wd-git-issue-103/git-issue-103.git (fetch)
origin  C:/r2g-wd-git-issue-103/git-issue-103.git (push)
```

Here's `git lfs env` output:

```
c:\r2g-wd-git-issue-103\git-issue-103>git lfs env
10:19:53.755597 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
10:19:53.763673 git.c:704               trace: exec: git-lfs env
10:19:53.763673 run-command.c:663       trace: run_command: git-lfs env
10:19:53.807819 trace git-lfs: exec: git 'version'
git-lfs/2.7.2 (GitHub; windows amd64; go 1.12.2; git 08a08ae0)
git version 2.22.0.windows.1

10:19:53.840380 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
10:19:53.984851 trace git-lfs: exec: git 'config' '-l'
Endpoint=https://c////r2g-wd-git-issue-103/git-issue-103.git/info/lfs (auth=none)
  SSH=c:///r2g-wd-git-issue-103/git-issue-103.git
LocalWorkingDir=C:\r2g-wd-git-issue-103\git-issue-103
LocalGitDir=C:\r2g-wd-git-issue-103\git-issue-103\.git
LocalGitStorageDir=C:\r2g-wd-git-issue-103\git-issue-103\.git
LocalMediaDir=C:\r2g-wd-git-issue-103\git-issue-103\.git\lfs\objects
LocalReferenceDirs=
TempDir=C:\r2g-wd-git-issue-103\git-issue-103\.git\lfs\tmp
ConcurrentTransfers=3
TusTransfers=false
BasicTransfersOnly=false
SkipDownloadErrors=false
FetchRecentAlways=false
FetchRecentRefsDays=7
FetchRecentCommitsDays=0
FetchRecentRefsIncludeRemotes=true
PruneOffsetDays=3
PruneVerifyRemoteAlways=false
PruneRemoteName=origin
LfsStorageDir=C:\r2g-wd-git-issue-103\git-issue-103\.git\lfs
AccessDownload=none
AccessUpload=none
DownloadTransfers=basic
UploadTransfers=basic
GIT_EXEC_PATH=C:/Program Files/Git/mingw64/libexec/git-core
GIT_LFS_PATH=C:\Program Files\Git LFS
GIT_TRACE=1
git config filter.lfs.process = "git-lfs filter-process"
git config filter.lfs.smudge = "git-lfs smudge -- %f"
git config filter.lfs.clean = "git-lfs clean -- %f"
10:19:54.021429 trace git-lfs: filepathfilter: rewrite ".git" as "**/.git/**"
10:19:54.021429 trace git-lfs: filepathfilter: rewrite "**/.git" as "**/.git"
10:19:54.022426 trace git-lfs: filepathfilter: accepting "tmp"
```

**Comment by bk2204** [comment]
Hey,

It is currently known that you can't use Git LFS to push to a local repository unless you use a [standalone transfer agent](https://github.com/git-lfs/git-lfs/blob/master/docs/custom-transfers.md). This isn't limited to Windows; it's the case everywhere.

You can set up a local instance of [our test server](https://github.com/git-lfs/lfs-test-server) if you want, or you can build your own standalone transfer agent. I'm not aware of any existing ones that handle local files.

**Comment by gdlxn-ibm** [comment]
Brian, thanks for getting back to me.

I'm new Git-LFS and simply followed the **Getting Started** instructions at https://git-lfs.github.com/.  In particular, step 3 states:

> 3. There is no step three. Just commit and push to GitHub as you normally would.
> 
>    git add file.psd
>    git commit -m "Add design file"
>    git push origin master

There's no mention of `git push`  not working to a local repository.  I would suggest updating the **Getting Started** instructions to mention this (and any other) known limitations.

**Comment by bk2204** [comment]
I've added support for `file:///` URLs (although not raw local paths) in #3748 which should support this use case.

**Comment by gdlxn-ibm** [comment]
I was about to ask questions regarding the standalone transfer agent I'm working on when I saw that you've already implemented a fix for `file:////` URLs.  Thanks so much for the quick fix.  How do I pick up the fix in #3748 so that I can try it in my environment?

**Comment by bk2204** [comment]
You can do something like the following:

1. `go get github.com/git-lfs/git-lfs`
1. `cd $GOPATH/src/github.com/git-lfs/git-lfs`
1. `git remote add bk2204 https://github.com/bk2204/git-lfs.git`
1. `git fetch bk2204`
1. `git checkout -b standalone-file bk2204/standalone-file`
1. `make`

**Comment by gdlxn-ibm** [comment]
Thanks for the instruction to get the fix.

I normally work on Windows.  The make command failed as it looks as though its made to run on Linux (or Unix).  I'll try on Linux to see that works better.  

I'm using Git-LFS as part of a tool I'm working on.  When will the fix for #3748 be made available in an official Git-LFS release that I can point users of my tool to?

**Comment by bk2204** [comment]
It will likely be in Git LFS 2.9.0. We usually make a release once a quarter, so it's likely a new release will be forthcoming in early October.

The make command should work in Git Bash, but it won't work in Powershell or the like. If you're running in a path with spaces in the name, you may want to run it as `BUILTIN_GC_FLAGS="" ASM_FLAGS="" make`. I know there's an issue there, but haven't gotten around to fixing it yet.

**Comment by gdlxn-ibm** [comment]
Using Git Bash, I seem to have gotten farther.  But I'm still having make problems:

```
$ make
which: no goimports in (/c/Users/GeoffAlexander/bin:/mingw64/bin:/usr/local/bin:/usr/bin:/usr/bin:/mingw64/bin:/usr/bin:/c/Users/GeoffAlexander/bin:/c/WINDOWS/system32:/c/WINDOWS:/c/WINDOWS/System32/Wbem:/c/WINDOWS/System32/OpenSSH:/c/WINDOWS/System32/WindowsPowerShell/v1.0:/c/UnxUtils-2013-04-24/usr/local/wbin:/c/UnxUtils-2013-04-24/bin:/c/Strawberry/c/bin:/c/Strawberry/perl/site/bin:/c/Strawberry/perl/bin:/c/Program Files (x86)/IBM/Personal Communications:/c/Program Files (x86)/IBM/Trace Facility:/c/Program Files/PuTTY:/c/Program Files/IBM/Java80/bin:/c/Program Files/IBM/Java80/jre/bin:/c/Program Files/IBM/TeamConcertBuild/scmtools/eclipse:/c/Program Files/ibm/gsk8/lib64:/c/Program Files (x86)/ibm/gsk8/lib:/c/PROGRA~1/IBM/SQLLIB/BIN:/c/PROGRA~1/IBM/SQLLIB/FUNCTION:/c/PROGRA~1/IBM/SQLLIB/SAMPLES/REPL:/c/apache-maven-3.6.0/bin:/c/Program Files/Git LFS:/cmd:/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/c/git-sizer-1.3.0:/c/Go/bin:/c/Users/GeoffAlexander/Documents/bin:/c/Users/GeoffAlexander/AppData/Local/Programs/Python/Python37/Scripts:/c/Users/GeoffAlexander/AppData/Local/Programs/Python/Python37:/c/Users/GeoffAlexander/AppData/Local/Programs/Python/Python36/Scripts:/c/Users/GeoffAlexander/AppData/Local/Programs/Python/Python36:/c/Users/GeoffAlexander/AppData/Local/Microsoft/WindowsApps:/c/Users/GeoffAlexander/go/bin:/usr/bin/vendor_perl:/usr/bin/core_perl)
go generate github.com/git-lfs/git-lfs/commands
```

The git-lfs.exe in $GOPATH/src/github.com/git-lfs/git-lfs\bin is not updated by the `make` command.

**Comment by bk2204** [comment]
That `which` error is ignorable. We run `goimports` to format code if it's present and don't if it's not.

You may need `goversioninfo` on Windows, which you should be able to get with `go get github.com/josephspurrier/goversioninfo/cmd/goversioninfo`. Once `goversioninfo` is in your path, you should be able to build successfully.

**Comment by gdlxn-ibm** [comment]
Thanks.  I'm new to `go`; I downloaded and used `go` for the first time today in order to build your `git-lfs` update.

I installed `goversioninfo` as you suggested.  I also figured out how to install `goimports` as well.  The `make` command now runs with no output.   However, the git-lfs.exe in $GOPATH/src/github.com/git-lfs/git-lfs/bin doesn't look to be updated by the `make` command.  How can I tell if the `make` command actually built your update?

**Comment by bk2204** [comment]
The binary isn't shipped as part of the repository, so you can simply remove the binary and re-run `make`, and if the file exists after that, it was properly built. You should also be able to run `git-lfs standalone-file </dev/null` (using the new binary in Git Bash) and have it exit silently without an error.

**Comment by gdlxn-ibm** [comment]
I tried deleting the `git-lfs.exe` binary after the `go get github.com/git-lfs/git-lfs` step,  After this, I found that the `make` command doesn't create a `git-lfs.exe` binary.  I've attached output of `make -d`.

Also, which `make` command should I be using?  The `make` command isn't included in my Git installation (https://git-scm.com/downloads).  I'm using the `make` command from UnxUtils (https://sourceforge.net/projects/unxutils/).
[make.txt](https://github.com/git-lfs/git-lfs/files/3455859/make.txt)

**Comment by bk2204** [comment]
Ah, that does appear to be the problem. We use the `.DEFAULT_GOAL` target, which was introduced in make 3.81, and you're using 3.78.1. You can either use the GNU Make version installed with chocolatey or you can simply run `make bin/git-lfs.exe`, which should invoke the proper target manually.

Sorry for not mentioning that earlier; I didn't realize that the version of make was going to be a problem.

**Comment by gdlxn-ibm** [comment]
Thanks.  Running `make bin/git-lfs.exe` worked in that it built a new `git-lfs.exe`.

**Comment by gdlxn-ibm** [comment]
I tried the new `git-lfs.exe` in my tool and got the following error:

```
15:18:19 - Executing command: ‘git push origin git-issue-103-stream’
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.<unknown>.locksverify false
batch request: missing protocol: "<unknown>"
error: failed to push some refs to 'file:///C:/r2g-wd-git-issue-103/git-issue-103.git'
```

The `git push` did not work as no files were pushed to `file:///C:/r2g-wd-git-issue-103/git-issue-103.git'.  Any idea what might be wrong?

**Comment by bk2204** [comment]
I've just pushed a new version which should fix path handling on Windows. You may want to try pulling that version in and rebuilding with it.

**Comment by bk2204** [comment]
Actually, you may want to hold off; I found an additional issue which I need to fix for Windows.

**Comment by gdlxn-ibm** [comment]
Thanks for getting back to me. I'll wait until you've delivered a fix for the additional issue you found.

**Comment by bk2204** [comment]
Okay, I've done some more testing, and the version that's there should be fine. Do note that if you're using Powershell, for some reason you either need to double-quote the file URL or escape the colon as `%3a`. 🤷‍♂

Git Bash works fine with either Unix-style file URLs or Windows-style file URLs.

**Comment by gdlxn-ibm** [comment]
I rebuilt `git-lfs.exe` with the latest code.  I'm still getting an error from `git push`:

```
c:\r2g-wd-git-issue-103\git-issue-103>git push origin git-issue-103-stream
15:00:21.872169 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
15:00:21.874189 git.c:439               trace: built-in: git push origin git-issue-103-stream
15:00:21.882284 run-command.c:663       trace: run_command: unset GIT_PREFIX; 'git-receive-pack '\''/C:/r2g-wd-git-issue-103/git-issue-103.git'\'''
15:00:22.005047 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
15:00:22.025215 git.c:439               trace: built-in: git receive-pack C:/r2g-wd-git-issue-103/git-issue-103.git
15:00:22.035250 run-command.c:663       trace: run_command: .git/hooks/pre-push origin file:///C:/r2g-wd-git-issue-103/git-issue-103.git
15:00:22.224404 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/libexec/git-core
15:00:22.226424 git.c:704               trace: exec: git-lfs pre-push origin file:///C:/r2g-wd-git-issue-103/git-issue-103.git
15:00:22.226424 run-command.c:663       trace: run_command: git-lfs pre-push origin file:///C:/r2g-wd-git-issue-103/git-issue-103.git
15:00:22.817760 trace git-lfs: exec: git 'version'
15:00:22.884560 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
15:00:23.047392 trace git-lfs: exec: git 'config' '-l'
15:00:23.082422 trace git-lfs: pre-push: refs/heads/git-issue-103-stream bda90392ef3790f93ae6eaa42593ece47ed8a6a3 refs/heads/git-issue-103-stream 0000000000000000000000000000000000000000
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.<unknown>.locksverify false
15:00:23.262814 trace git-lfs: tq: running as batched queue, batch size of 100
15:00:23.264809 trace git-lfs: run_command: git rev-list --stdin --objects --not --remotes=origin --
15:00:23.334891 trace git-lfs: tq: sending batch of size 1
batch request: missing protocol: "<unknown>"/s
Uploading LFS objects:   0% (0/1), 0 B | 0 B/s, done
error: failed to push some refs to 'file:///C:/r2g-wd-git-issue-103/git-issue-103.git'

c:\r2g-wd-git-issue-103\git-issue-103>git remote -v
15:02:53.880952 exec-cmd.c:238          trace: resolved executable dir: C:/Program Files/Git/mingw64/bin
15:02:53.882975 git.c:439               trace: built-in: git remote -v
origin  file:///C:/r2g-wd-git-issue-103/git-issue-103.git (fetch)
origin  file:///C:/r2g-wd-git-issue-103/git-issue-103.git (push)
```

Please let know if there is more information I can collect to help determine what the problem is.

**Comment by bk2204** [comment]
When you run `git lfs --version` and `git-lfs --version`, what version do they produce? If it's not 2.8.0, then you're likely using the old version in your Git installation, which you'll need to remove (there's two `git-lfs.exe` binaries to remove) before it takes effect. I ran into this myself.

**Comment by gdlxn-ibm** [comment]
I was wondering if that might be the case.  Running `git-lfs --version` shows 2.8.0:

```
C:\WINDOWS\system32>git-lfs --version
git-lfs/2.8.0 (GitHub; windows amd64; go 1.12.7; git bb05cf50)
```

However, `git lfs --version` shows 2.7.2:

```
C:\WINDOWS\system32>git lfs --version
git-lfs/2.7.2 (GitHub; windows amd64; go 1.12.2; git 08a08ae0)
```

which suggests that `git lfs` is still picking up the old Git LFS.  

I find two git-lfs.exe binaries in my path:

```
C:\WINDOWS\system32>where git-lfs
C:\Program Files\Git LFS\git-lfs.exe
C:\Program Files\Git\cmd\git-lfs.exe
```

`C:\Program Files\Git LFS\git-lfs.exe` is the binary that I replaced with the build version.  `C:\Program Files\Git\cmd\git-lfs.exe` is quite small as compared to `C:\Program Files\Git LFS\git-lfs.exe`:

```
C:\WINDOWS\system32>ls -l "C:\Program Files\Git LFS\git-lfs.exe"
-rwxrwxrwx   1 user     group    10369536 Aug  2 14:47 C:\Program Files\Git LFS\git-lfs.exe

C:\WINDOWS\system32>ls -l "C:\Program Files\Git\cmd\git-lfs.exe"
-rwxrwxrwx   1 user     group       43544 Jun  8 06:14 C:\Program Files\Git\cmd\git-lfs.exe
```

I was thinking that it's simply a small wrapping / stub program used by the `git lfs` command.   Do I need to replace `C:\Program Files\Git\cmd\git-lfs.exe` with the build version as wel?.  Or is there something else I need to do to have `git lfs` pick up the new Git LFS?

**Comment by bk2204** [comment]
I'm not sure if you need to replace the wrapper program. You can try leaving it in place and replacing the other one, and if both commands I mentioned above produce the 2.8.0 version, then you should be fine. If that doesn't work, then replacing them would be the best course of action.

**Comment by gdlxn-ibm** [comment]
I found a third `git-lfs.exe` in `C:\Program Files\Git\mingw64\bin` that I had to replace with the build version (see my comment in Git LFS Issue #2587 for details).  Once I did that `'git lsf --version` reports version 2.8.0 (new build) and more importantly my local `git push` with a large file now works:

```
c:\r2g-wd-git-issue-103\git-issue-103>git push origin git-issue-103-stream
Uploading LFS objects: 100% (1/1), 0 B | 0 B/s, done
Enumerating objects: 16, done.
Counting objects: 100% (16/16), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (14/14), 848.19 KiB | 291.00 KiB/s, done.
Total 14 (delta 2), reused 0 (delta 0)
To file:///C:/r2g-wd-git-issue-103/git-issue-103.git
 * [new branch]      git-issue-103-stream -> git-issue-103-stream
```

**Comment by bk2204** [comment]
Terrific. I'll merge that branch, then. Thanks for testing.
