### ISSUE TITLE
git push fails with certifcate error but actually lfs failed with wrong credentials

### ISSUE THREAD

**Issue by LordOfDragons** [git-lfs/git-lfs#4331]
I've set up a test git repository with LFS support against a GIT server in the LAN using Apache and Let's Encrypt certificates.

I've commited and pushed first 2 regular source files. These commit and push correctly without error.

Then I added 2 binary files tracked with LFS and pushing fails with this error:
```
GIT_TRACE=1 git push
18:38:32.818721 git.c:439               trace: built-in: git push
18:38:32.818859 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://XXX@git.rptd.ch/repository/lfstest
18:38:32.829261 run-command.c:663       trace: run_command: 'git credential-cache --timeout=86400 get'
18:38:32.831637 git.c:703               trace: exec: git-credential-cache --timeout=86400 get
18:38:32.831669 run-command.c:663       trace: run_command: git-credential-cache --timeout=86400 get
18:38:32.834052 run-command.c:663       trace: run_command: 'git credential-cache --timeout=86400 store'
18:38:32.836007 git.c:703               trace: exec: git-credential-cache --timeout=86400 store
18:38:32.836033 run-command.c:663       trace: run_command: git-credential-cache --timeout=86400 store
18:38:32.838135 run-command.c:663       trace: run_command: .git/hooks/pre-push origin https://XXX@git.rptd.ch/repository/lfstest
18:38:32.840258 git.c:703               trace: exec: git-lfs pre-push origin https://XXX@git.rptd.ch/repository/lfstest
18:38:32.840286 run-command.c:663       trace: run_command: git-lfs pre-push origin https://XXX@git.rptd.ch/repository/lfstest
18:38:32.844386 trace git-lfs: exec: git 'version'
18:38:32.847635 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
18:38:32.849866 trace git-lfs: exec: git 'config' '-l'
18:38:32.851126 trace git-lfs: pre-push: refs/heads/master acab5f6454f23641c6be1e25d896b8205afda95a refs/heads/master 300d46fafdfd5a357fd1e2c49e38e8ea844754cd
18:38:32.873484 trace git-lfs: HTTP: POST https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/locks/verify
Remote "origin" does not support the LFS locking API. Consider disabling it with:
  $ git config lfs.https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs.locksverify false
18:38:32.877240 trace git-lfs: tq: running as batched queue, batch size of 100
18:38:32.877347 trace git-lfs: run_command: git rev-list --objects --ignore-missing --not --remotes=origin --stdin --
18:38:32.879190 trace git-lfs: tq: sending batch of size 2                                                                                               
18:38:32.879358 trace git-lfs: api: batch 2 files
18:38:32.879408 trace git-lfs: HTTP: POST https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch
18:38:32.907991 trace git-lfs: api error: Post "https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch": x509: certificate signed by unknown authority
batch response: Post "https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch": x509: certificate signed by unknown authority
error: failed to push some refs to 'https://XXX@git.rptd.ch/repository/lfstest'
```

Checking the server logs shows LFS failed to send the correct credentials:
```
[Wed Dec 02 18:38:32.862494 2020] [auth_basic:error] [pid 23107:tid 140131629528640] [client 192.168.1.20:37802] AH01617: user XXX: authentication failure for "/repository/lfstest/info/refs": Password Mismatch
```

GIT sends the correct credentials but LFS fails to send the correct credentials.

I've googled so far that LFS does not use the same Credential-Store as GIT does (I'm using [credential] helper = cache). So I would expect LFS to ask for a password then but it does not and instead failed.

The question now is where the bug is:
1) LFS fails to send authentication correctly (error message on server from Apache)
2) LFS fails for some reason with Let's Encrypt certificates (a google report lists this as a potential problem too)

Point 2 doesn't make sense to me since GIT does not have troubles too so I'm with point 1 since Apache claims wrong password is send. Looks like LFS somehow bugs out with the authentication. Any pointers?

**Comment by bk2204** [comment]
Hey,

Sorry to hear you're having trouble.

First, I think you are actually seeing a problem with certificates.  The certificate store used by Git LFS is the system one.  You didn't fill out the issue template, so we don't know what OS you're using, but if you're using a Linux variant, you may need to install the `ca-certificates` package or equivalent in your distro.  Can you say a little about what OS and version you're using, and what versions of Git and Git LFS you're using, and if you have any `http.*` variables in your Git config on the client (`git config -l | grep -F http.`)?

I know that Git LFS does work with Let's Encrypt certificates when properly configured because I implemented Kerberos support for Git LFS against my own Git server using Apache with a Let's Encrypt certificate.  Do note that you need to send all the relevant intermediates as part of your chain, which it looks like you're doing (according to a test I did against that server), but that is a potential failure case.  Note that some browsers fill in intermediates, so they are not a good test for this case.

I think what you're seeing in your logs is actually Git and not Git LFS.  The `/info/refs` endpoint is used by Git, but not by Git LFS, so it looks like that request isn't one from Git LFS.

**Comment by LordOfDragons** [comment]
OS is GenToo on both client and server

Software packages installed:
```
app-misc/ca-certificates : Latest version installed: 20200601.3.53
dev-vcs/git : Latest version installed: 2.26.2
dev-vcs/git-lfs : Latest version installed: 2.11.0
```

There is
```
http.sslcainfo=/mnt/server/home/public/admin/cacert_root.crt
```
in the git config but it is outdated and not used anymore since the switch to Let's Encrypt certificates. GIT does not care so I did not remove it yet.

**Comment by LordOfDragons** [comment]
I tried now removing that deprecated cacert line. It is still failing but the error has now changed.

On the client side:
```
GIT_TRACE=1 git push
20:50:52.354193 git.c:439               trace: built-in: git push
20:50:52.354314 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://XXX@git.rptd.ch/repository/lfstest
20:50:52.371680 run-command.c:663       trace: run_command: 'git credential-cache --timeout=86400 get'
20:50:52.373825 git.c:703               trace: exec: git-credential-cache --timeout=86400 get
20:50:52.373852 run-command.c:663       trace: run_command: git-credential-cache --timeout=86400 get
20:50:52.376020 run-command.c:663       trace: run_command: 'git credential-cache --timeout=86400 store'
20:50:52.378011 git.c:703               trace: exec: git-credential-cache --timeout=86400 store
20:50:52.378042 run-command.c:663       trace: run_command: git-credential-cache --timeout=86400 store
20:50:52.380277 run-command.c:663       trace: run_command: .git/hooks/pre-push origin https://XXX@git.rptd.ch/repository/lfstest
20:50:52.382353 git.c:703               trace: exec: git-lfs pre-push origin https://XXX@git.rptd.ch/repository/lfstest
20:50:52.382379 run-command.c:663       trace: run_command: git-lfs pre-push origin https://XXX@git.rptd.ch/repository/lfstest
20:50:52.385782 trace git-lfs: exec: git 'version'
20:50:52.389030 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
20:50:52.391155 trace git-lfs: exec: git 'config' '-l'
20:50:52.392300 trace git-lfs: pre-push: refs/heads/master acab5f6454f23641c6be1e25d896b8205afda95a refs/heads/master 300d46fafdfd5a357fd1e2c49e38e8ea844754cd
20:50:52.424435 trace git-lfs: HTTP: POST https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/locks/verify
20:50:52.472566 trace git-lfs: HTTP: 403
WARNING: Authentication error: Authentication required: Authorization error: https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/locks/verify
Check that you have proper access to the repository
20:50:52.472659 trace git-lfs: tq: running as batched queue, batch size of 100
20:50:52.472756 trace git-lfs: run_command: git rev-list --objects --ignore-missing --not --remotes=origin --stdin --
20:50:52.475821 trace git-lfs: tq: sending batch of size 2                                                                                               
20:50:52.476024 trace git-lfs: api: batch 2 files
20:50:52.476078 trace git-lfs: HTTP: POST https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch
20:50:52.481421 trace git-lfs: HTTP: 403
20:50:52.481462 trace git-lfs: api error: Authorization error: https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch
Check that you have proper access to the repository
batch response: Authorization error: https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch
Check that you have proper access to the repository
error: failed to push some refs to 'https://XXX@git.rptd.ch/repository/lfstest'
```

On the server side:
```
[Wed Dec 02 20:50:52.370963 2020] [auth_basic:error] [pid 23107:tid 140131025548864] [client 192.168.1.20:38594] AH01617: user XXX: authentication failure for "/repository/lfstest/info/refs": Password Mismatch
[Wed Dec 02 20:50:52.413347 2020] [auth_basic:error] [pid 23103:tid 140130664826432] [client 192.168.1.20:38596] AH01617: user XXX: authentication failure for "/repository/lfstest/info/refs": Password Mismatch
[Wed Dec 02 20:50:52.472074 2020] [authz_core:error] [pid 23107:tid 140130975192640] [client 192.168.1.20:38598] AH01630: client denied by server configuration: /var/www/git/repository/lfstest.git
[Wed Dec 02 20:50:52.480951 2020] [authz_core:error] [pid 23103:tid 140130648041024] [client 192.168.1.20:38600] AH01630: client denied by server configuration: /var/www/git/repository/lfstest.git
```

In addition to the "Password Mismatch" line two line lines show up. That would look more like Apache Configuration problem but GIT commits without LFS files included do work. Here is the excert from the config for this repository:
```
<Location /repository/lfstest>
        AuthType Basic
        ... (authentication stuff) ...
        <Limit GET PUT POST DELETE PROPPATCH MKCOL COPY MOVE LOCK UNLOCK>
                Require user XXX
        </Limit>
</Location>
```

Could it be LFS requires some additional permissions?

**Comment by LordOfDragons** [comment]
Just noticed... why does LFS append ".git" to the URL? It seems to ask for "git.rptd.ch/repository/lfstest.git" which is wrong. It should ask for "git.rptd.ch/repository/lfstest".

Is this a bug or a feature?

**Comment by bk2204** [comment]
Git LFS always appends a `.git` if it's missing when it does repository autodiscovery.  Git will try several options for repository autodiscovery but Git LFS does not.  You can either set the URL explicitly with `lfs.url` (e.g., `https://git.rptd.ch/repository/lfstest/info/lfs`)  or you can use `.git` on the end of your repositories, which is customary anyway.

**Comment by LordOfDragons** [comment]
Just asking since I remember LFS stating it simply "appends" to the URL. This should not change the URL, should it?

**Comment by LordOfDragons** [comment]
I changed now the repository name on the server to "lfstest.git". This changes the error now back to the "Password Mismatch" one. Still no luck:
 ```
22:53:00.388859 git.c:439               trace: built-in: git push
22:53:00.389024 run-command.c:663       trace: run_command: GIT_DIR=.git git-remote-https origin https://XXX@git.rptd.ch/repository/lfstest.git
22:53:00.406380 run-command.c:663       trace: run_command: 'git credential-cache --timeout=86400 get'
22:53:00.408539 git.c:703               trace: exec: git-credential-cache --timeout=86400 get
22:53:00.408566 run-command.c:663       trace: run_command: git-credential-cache --timeout=86400 get
22:53:00.410993 run-command.c:663       trace: run_command: 'git credential-cache --timeout=86400 store'
22:53:00.412996 git.c:703               trace: exec: git-credential-cache --timeout=86400 store
22:53:00.413033 run-command.c:663       trace: run_command: git-credential-cache --timeout=86400 store
22:53:00.415364 run-command.c:663       trace: run_command: .git/hooks/pre-push origin https://XXX@git.rptd.ch/repository/lfstest.git
22:53:00.417530 git.c:703               trace: exec: git-lfs pre-push origin https://XXX@git.rptd.ch/repository/lfstest.git
22:53:00.417558 run-command.c:663       trace: run_command: git-lfs pre-push origin https://XXX@git.rptd.ch/repository/lfstest.git
22:53:00.421317 trace git-lfs: exec: git 'version'
22:53:00.424616 trace git-lfs: exec: git '-c' 'filter.lfs.smudge=' '-c' 'filter.lfs.clean=' '-c' 'filter.lfs.process=' '-c' 'filter.lfs.required=false' 'rev-parse' 'HEAD' '--symbolic-full-name' 'HEAD'
22:53:00.426666 trace git-lfs: exec: git 'config' '-l'
22:53:00.427807 trace git-lfs: pre-push: refs/heads/master acab5f6454f23641c6be1e25d896b8205afda95a refs/heads/master 300d46fafdfd5a357fd1e2c49e38e8ea844754cd
22:53:00.459523 trace git-lfs: tq: running as batched queue, batch size of 100
22:53:00.459654 trace git-lfs: run_command: git rev-list --objects --ignore-missing --not --remotes=origin --stdin --
22:53:00.461542 trace git-lfs: tq: sending batch of size 2                                                                                               
22:53:00.461782 trace git-lfs: api: batch 2 files
22:53:00.461950 trace git-lfs: creds: git credential fill ("https", "git.rptd.ch", "")
22:53:00.462704 git.c:439               trace: built-in: git credential fill
22:53:00.462800 run-command.c:663       trace: run_command: 'git credential-cache --timeout=86400 get'
22:53:00.464627 git.c:703               trace: exec: git-credential-cache --timeout=86400 get
22:53:00.464654 run-command.c:663       trace: run_command: git-credential-cache --timeout=86400 get
22:53:00.466040 trace git-lfs: Filled credentials for https://XXX@git.rptd.ch/repository/lfstest.git
22:53:00.466376 trace git-lfs: HTTP: POST https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch
22:53:00.509979 trace git-lfs: HTTP: 404
22:53:00.510045 trace git-lfs: api error: Repository or object not found: https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch
Check that it exists and that you have proper access to it
batch response: Repository or object not found: https://XXX@git.rptd.ch/repository/lfstest.git/info/lfs/objects/batch
Check that it exists and that you have proper access to it
error: failed to push some refs to 'https://XXX@git.rptd.ch/repository/lfstest.git'
```

server:
```
[Wed Dec 02 22:53:00.406155 2020] [auth_basic:error] [pid 27542:tid 140131000370752] [client 192.168.1.20:38994] AH01617: user XXX: authentication failure for "/repository/lfstest.git/info/refs": Password Mismatch
[Wed Dec 02 22:53:00.449095 2020] [auth_basic:error] [pid 27542:tid 140132048946752] [client 192.168.1.20:38996] AH01617: user XXX: authentication failure for "/repository/lfstest.git/info/refs": Password Mismatch
```

**Comment by bk2204** [comment]
Okay, this is a different problem.  It looks like you don't have an LFS server running.  Unlike Git, Git LFS doesn't support a DAV-based protocol; it requires an active server that can satisfy requests.  Have you set one up?  If not, we have one you could set up behind Apache as proxy at https://github.com/git-lfs/lfs-test-server/.

**Comment by LordOfDragons** [comment]
That's not going to work. GIT access from the Internet is only allowed over HTTPS.

**Comment by bk2204** [comment]
I'm pretty sure it will in fact work.

Git has two HTTP-based protocols: the dumb (DAV-based) one and the smart one.  The smart protocol requires a CGI binary to serve data; it still uses HTTP, but it isn't just a set of static files.  Similarly, the Git LFS protocol, while different than the Git protocol, is HTTP-based, but it also requires a smart server and can't deal with a static set of files.

If you set up the lfs-test-server behind Apache, it will still be accessible over HTTPS.

**Comment by LordOfDragons** [comment]
The problem has been solved. It had been a problem with the Git hosting software having a file permission issue. My lfs-test succeeded now so I think this issue can be closed.
