### ISSUE TITLE
git lfs pull: failed to copy downloaded file: due to concurrent cleanup of tmp dir from clean filter command

### ISSUE THREAD

**Issue by acolinisi** [git-lfs/git-lfs#4488]
**Describe the bug**

`git lfs pull` via `file://` local path endpoint fails for some subset of the blob objects with the following error:
```
failed to copy downloaded file: cannot replace "/REPOPATH/.git/lfs/objects/d7/3f/d73f32c248a4591139a6b17777c80d4deab6b414ec2b3d21d0a24be348c476ab" with "/REPOPATH/.git/lfs/tmp/download217213722"
```

**To Reproduce**

This is reproduces every time deterministically for me, but I can't guarantee it will easily reproduce for you because it might be a function of the set of the blob files. So, this is just to illustrate that the use case is vanilla.
 
    git init --bare barefoo
    git lfs install
    
    git init foo
    git lfs track ".tar.gz"
    # add a few hundred of .tar.gz archives each of size between [1KB, 3GB]
    git add .gitattributes
    git add foo.tar.gz
    git remote add up file://$(realpath ../barefoo)
    git push up
    
    git lfs uninstall
    git clone file://$(realpath barefoo)  bar
    git lfs pull

Some objects will fail to be added (you can check that some of the files are still pointers) and for each failed object the above error or similar will be shown: either failure of a rename or a hardlink operation. There is some variation in the exact error depending on the timing, i.e. on which of the IO syscalls fails to find a temporary file after it is being (inadvertently) deleted (see diagnosis below).

**Expected behavior**
git lfs pull should succeed

**System environment**
Linux ppc64le
lsf 2.13.3 on ppc64le from official binary release
Also, built master 94245ec834c7f938ec3a7808f73e9bd1d2b04f0a from source with Go 1.15.6 -- same, no surprise.

**Diagnosis**

The problem is simple: rename/hardlink operations fail because the source file is indeed removed by a concurrent git-lfs process. Confirmed in strace. During running of `git lfs pull`, the clean filter command is invoked `git-lfs clean -- %f` for some files, but part of any invocation of git-lfs is to cleanup the temp directory at the end. That cleanup deletes temporary files that have been created and are being used by the pull/download process.

The rename/hardllink that fails is in lfs/util.go LinkOrCopy/CopyFileContents or in tq/custom.go in DoTransfer within tools.RenameFileCopyPermissions. The code path in the second `git-lfs` process that leads to the bad unlink() syscall that causes the rename to fail is:

    git-lfs.go:main() -> commands.Cleanup -> fs/cleanup.go:cleanupTmp()

I don't have the reason for why the clean filter is invoked during `git lfs pull` but I assume that's normal operation. If not, then that is the root cause.

This is the sequence of events, bad unlink() before the failing rename(), note that they come from two different PIDs, so I show the process tree first.

Descendants of the main process that is trying to do the lfs pull:
```
91073 execve("/usr/bin/sh", ["sh", "-c", "git-lfs standalone-file"], [/* 124 vars */]) = 0

91073 clone(child_stack=0x7fff5b90e8f0, 
flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD
_CLEARTID, parent_tidptr=0x7fff5b90f1b0, tls=0x7fff5b9168e0, child_tidptr=0x7fff5b90f1b0) = 91075
91075 clone(child_stack=0x7fff5a8ee8f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD
_CLEARTID, parent_tidptr=0x7fff5a8ef1b0, tls=0x7fff5a8f68e0, child_tidptr=0x7fff5a8ef1b0) = 91077
91077 clone(child_stack=0x7fff5903e8f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD
_CLEARTID, parent_tidptr=0x7fff5903f1b0, tls=0x7fff590468e0, child_tidptr=0x7fff5903f1b0) = 91081
```

Descendants of the concurrent process that will issue the bad unlink:
```
91507 execve("/bin/sh", ["/bin/sh", "-c", "git-lfs clean -- 'distfiles/libS"..., "git-lfs clean -- 'distfiles/libS"...], [/* 126 vars */]) = 0
91507 clone(child_stack=0x7fff7bffe8f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD
_CLEARTID, parent_tidptr=0x7fff7bfff1b0, tls=0x7fff7c0068e0, child_tidptr=0x7fff7bfff1b0) = 91509
91509 clone(child_stack=0x7fff80e4e8f0, flags=CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD
_CLEARTID, parent_tidptr=0x7fff80e4f1b0, tls=0x7fff80e568e0, child_tidptr=0x7fff80e4f1b0) = 91511
```

The rename call from former process that gets doomed by the unlink call from latter process:
```
91081 openat(AT_FDCWD, "/REPO/.git/lfs/tmp/download124879086676804469", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0600 <unfinished ...>
91081 fchmodat(AT_FDCWD, "/REPO/.git/lfs/tmp/download124879086676804469", 0664) = 0

91511 unlinkat(AT_FDCWD, "/REPO/.git/lfs/tmp/download124879086676804469", 0) = 0

91081 renameat(AT_FDCWD, "/REPO/.git/lfs/tmp/download124879086676804469", AT_FDCWD, "/REPO/.git/lfs/tmp/download124879086") = -1 ENOENT (No such file or directory)
```

** Workaround **

One ugly workaround (that doesn't require re-build of git-lfs) is to point clean filter command away from the actual repo, so that their cleanup of the temp dir won't affect the main repo's temp dir. The clean command just hashes the file, it doesn't need any config from the main repo.

```
DUMMY_REPO=.git-lfs-dummy
git init --bare "${DUMMY_REPO}"
git config filter.lfs.clean "git --git-dir ${DUMMY_REPO} lfs clean -- %f"

git lfs pull
```

This workaround fixes the issue for me. What also fixes the issue is if I remove all the code from cleanupTmp function in fs/cleanup.go.

I would submit a PR, but I am not sure whether this git lfs clean call is supposed to be happening or not. The right fix will depend on that.

If the concurrent clean command during pull command is normal, then one way would be to dedicate separate temp subdirectories to different command:`lfs/tmp/COMMAND/*`, so that the download process ends up creating temp files at paths `lfs/tmp/pull/downloadNNNNN` intead of at path `lfs/tmp/downloadNNNNN` and the `git-lfs clean` invocation would only walk and clean `lfs/tmp/clean/*`.

**Comment by bk2204** [comment]
Hey,

Thanks for the report and the extremely thorough analysis.  I think the easiest thing to do here is just to avoid always removing files that don't look like files associated with object IDs.  That should make us fall back to waiting an hour before deleting files, which should solve this problem.

I've proposed such a change in #4490.  Can you look and see if it solves your problem?

**Comment by acolinisi** [comment]
Thanks, but I'm afraid that the issue still happens with #4490 applied.

How do I enable the 'tracerx.Printf()' output?

**Comment by slonopotamus** [comment]
@bk2204 Is this a regression from some recent change? Download code that juggles with tmp files is couple of years old already.

**Comment by bk2204** [comment]
> Thanks, but I'm afraid that the issue still happens with #4490 applied.
> 
> How do I enable the 'tracerx.Printf()' output?

You can do so with `GIT_TRACE=1`.

> @bk2204 Is this a regression from some recent change? Download code that juggles with tmp files is couple of years old already.

It shouldn't be.  Support for `file` URLs came in with 2.10, so this would have been around since about that time.

**Comment by acolinisi** [comment]
First a separate issue (maybe fork a separate Issue):  I did try `GIT_TRACE=1` when debuggign initially but found that it wasn't taking effect at the relevant tracerx statements in cleanup.go. And, I re-confirmed this now: os.RemoveAll(path) on cleanup.go:48 is executing, but I don't get the preceding tracerx statement on the stderr/stdout; and if I replace tracerx with `fmd.Fprintf(os.Stderr, ...)` then I get the output. Perhaps a race with process exit -- maybe the log is not being flushed. (This print is happening close to end of process, hence this guess.)

We might have our answer to the original issue: 
```
Removing old tmp object file of age 86h31m35.262630873s:
/PATH/.git/lfs/tmp/download864343895
```

From the clone from which the git lfs pull is being done via `file://`:
```
stat lfs/objects/dc/e5/dce5110dd1530660cfae084df719091d83a6622509956a89876df134773ced81
  File: lfs/objects/dc/e5/dce5110dd1530660cfae084df719091d83a6622509956a89876df134773ced81
  Size: 14271           Blocks: 32         IO Block: 16777216 regular file
Device: 2dh/45d Inode: 3052511820  Links: 3
Access: (0644/-rw-r--r--)  Uid: (16380/  acolin)   Gid: (28322/  csc436)
Access: 2021-04-27 16:05:54.825765802 -0000
Modify: 2021-04-25 00:35:50.742314632 -0000
Change: 2021-04-27 16:05:54.825198000 -0000
 Birth: -
 ```

So, #4490 is necessary but not sufficient. The check for 1h age of the temp file won't work. The fix would be simple: just replace `info.ModTime()` with `info.AccessTime()`.... except that Go standard library decided that nobody could possibly need any of the other timestamps in the stat structure?: https://golang.org/pkg/io/fs/#FileInfo

Given that... a hacky workaround might be to force the modification timestamp after "download" (do equivalent of `touch -d YYYY-MM-DD foo`), or alternatively, not preserve the timestamp when doing the "download"(/copy/link) (don't know how the custom transfer adapter is "downloading" the file exactly).

**Comment by slonopotamus** [comment]
Access time won't work on filesystems mounted with `noatime`.

**Comment by bk2204** [comment]
I've pushed up what should be an additional fix to #4490.  Can you test with that?

**Comment by acolinisi** [comment]
Yes. The pull is successful with the latest #4490 applied. Thank you.

Modifying the source does not sound too satisfying a fix, though. I'm afraid the fix snowballed. If we take a step back, then this 'age' logic is what asks to be revised. The criteria in the cleanup should be tightened from a hacky "age > 1h" to based on the path (my earlier suggestion, segrate temp dir per command) or  based on filename: any clean logic should only remove files that its owner created and not worry about other files that happen to be there. But, I'm sure you see all this... so whatever, I'm happy to have a working git-lfs, hope it makes it in the next release.

**Comment by slonopotamus** [comment]
As I said in https://github.com/git-lfs/git-lfs/pull/4490#discussion_r621446766, I believe there is a better way to fix this, but it requires restructuring download code (it is currently impossible to hardlink file directly from source lfs-storage to destination bypassing tmp dir completely).

**Comment by bk2204** [comment]
> Modifying the source does not sound too satisfying a fix, though. I'm afraid the fix snowballed. If we take a step back, then this 'age' logic is what asks to be revised. The criteria in the cleanup should be tightened from a hacky "age > 1h" to based on the path (my earlier suggestion, segrate temp dir per command) or based on filename: any clean logic should only remove files that its owner created and not worry about other files that happen to be there. But, I'm sure you see all this... so whatever, I'm happy to have a working git-lfs, hope it makes it in the next release.

We can't actually clean up only the files that the process's owner created because people interrupt commands with Ctrl-C (I do this frequently) and we'd leave a lot of cruft behind.  This is a problem when you interrupt Git and it's packing things, because then you get a partially written pack that hangs out in your repository forever and tends to be large.

If we used a per-type-of-command temporary directory, we'd still run into the same problem if people ran multiple concurrent operations on the same repository, since we prefer to link by default (which is far more efficient when possible).  We could use a temporary directory for this particular job and only recurse into temporary directories if they're at least an hour old.  Let me try that as a possibility and you can see what you think about how that works for you.

> As I said in [#4490 (comment)](https://github.com/git-lfs/git-lfs/pull/4490#discussion_r621446766), I believe there is a better way to fix this, but it requires restructuring download code (it is currently impossible to hardlink file directly from source lfs-storage to destination bypassing tmp dir completely).

Yes, that requires that we no longer be a standalone transfer adapter, which means we have to adjust this code to integrate it more closely.  Considering the amount of work to handle that case for the SSH adapter was been pretty significant and that when doing so we wouldn't verify the hash of the object we're downloading (which could let corruption go undetected), I'm not super excited about that possibility.

**Comment by slonopotamus** [comment]
> people interrupt commands with Ctrl-C

But you _can_ handle CTRL+C and cleanup properly. You can't handle segfault or powerloss, but thoseeventsaren't supposedto be regular.

**Comment by bk2204** [comment]
> But you _can_ handle CTRL+C and cleanup properly. You can't handle segfault or powerloss, but those events aren't supposed to be regular.

Yes, if you know exactly what files you were processing at the time and make that available in a global way to the signal handler, which is difficult in most programs because it requires keeping global state or having places throughout the code where you check for SIGINT.  It's not impossible, but this is a lot easier when you have a singleton process such as a daemon.

Anyway, I've pushed a new update to #4490 that should use a per-transfer agent temporary directory for our hard linking needs, which should address most of the concerns about this approach.  @acolinisi, can you verify that this also solves the problem?

**Comment by acolinisi** [comment]
Yes. Confirmed that #4490 36dc2aa3 solves the issue as well. Thank you.

Yeah, I see that the requirements you have make this problem tricky -- essentially the cleanup entity does need to be cleaning up files that have been created by other entities. So, this eliminates approaches like:
* cleanup "your own" files on signal: good, but doesn't solve unclean termination, which either brings us back to square 1 or leaves the need for an extra user-facing "gc" command, which is not good, and that gc command would require locking files against other concurrent uses of the repository.
* keep state of currently running tasks and check that state from the cleanup task (i.e. if owner of temp file is known to be still running then don't remove the file): but can't think of a way to do this such that it works for repos on a shared file system used by different machines where you can't lookup running processes (whithout relying on some age criteria).

So, yeah... @slonopotamus approach of changing download code or your fix is what remains. Thanks for the fix and explanation.
