### ISSUE TITLE
Packages on packagecloud.io not accessible anymore

### ISSUE THREAD

**Issue by webmaster128** [git-lfs/git-lfs#5197]
Hey there!

For a long time I installed the git-lfs .dep in a CI system via packagecloud.io. However, today I noticed a "Payment required" / "HTTP 402" in my CI. It seems like something is wrong here.

* Download URL: https://packagecloud.io/github/git-lfs/packages/ubuntu/focal/git-lfs_2.12.1_amd64.deb/download.deb
* Project page: https://packagecloud.io/github/git-lfs
* Search results: https://packagecloud.io/app/github/git-lfs/search?q=git-lfs_&filter=all&filter=all&dist=ubuntu%2Ffocal

Is this something you indent to fix? Thanks a lot!

**Comment by AVK636** [comment]
Doesn't seem to be the first time this problem occurs 😄 
- https://github.com/actions/runner-images/issues/1983
- https://github.com/git-lfs/git-lfs/issues/4548
I think we just have to wait until they fixed the problem.

**Comment by humberaquino** [comment]
Having same issue and It looks like this happened in the past too https://github.com/git-lfs/git-lfs/issues/4548
@bk2204 can you help us with this? 🙏

**Comment by jose-workpath** [comment]
We're seeing the same error in our CI. If you are not using git-lfs, you can do what someone suggested in a thread [here](https://github.com/r-lib/actions/issues/204#issuecomment-722083253) and remove the git-lfs package as a temporary workaround.

It worked for me with:

```sh
sudo rm /etc/apt/sources.list.d/github_git-lfs.list
```

**Comment by NunchakusLei** [comment]
> We're seeing the same error in our CI. If you are not using git-lfs, you can do what someone suggested in a thread [here](https://github.com/r-lib/actions/issues/204#issuecomment-722083253) and remove the git-lfs package as a temporary workaround.
> 
> It worked for me with:
> 
> ```shell
> commands:
>   - sudo rm /etc/apt/sources.list.d/github_git-lfs.list
>   # The rest of your commands:
>   - sudo apt-get update
> ```

Giving a try on our CI and works. Thanks for the walk around suggestion.

**Comment by caius** [comment]
Looks like this has been fixed now, thanks to whomever was involved!

**Comment by chrisd8088** [comment]
This looks like a billing issue again and I fear whatever service has been restored may be temporary, as I don't think we've tracked down a proper resolution yet.  With the U.S. holiday my queries to try to locate the appropriate resources may not be answered immediately, unfortunately.

**Comment by chrisd8088** [comment]
OK, with kind assistance from GitHub and Packagecloud, the problem should now be fully resolved.  It may have been the result of someone going on parental leave.

**Comment by MusfiqDehan** [comment]
The issue is not solved yet. Removing git lfs is the only solution. I am using Ubuntu 23.10.

**Comment by chrisd8088** [comment]
@MusfiqDehan -- could you open a fresh issue, rather than comment on an old one which was, indeed, resolved?  Please include all the details you can, such as the Git LFS version, OS version and platform, and full set of commands you are attempting to use.  Thank you!
